### ISSUE TITLE
实现了程序之后无法登陆

### ISSUE THREAD

**Issue by xiaodeme-aha** [MiChuancey/jmuSupplicant#2]
在ipk程序安装之后
一直认证不上程序这是什么原因呢

**Comment by MiChuancey** [comment]
错误提示发一下， 可以加群讨论：789745005 比较方便

**Comment by CChuancey** [comment]
> 在ipk程序安装之后
> 一直认证不上程序这是什么原因呢

错误提示发一下， 可以加群讨论：789745005 比较方便
