### ISSUE TITLE
关于编译工具链的获取

### ISSUE THREAD

**Issue by GnaixEuy** [MiChuancey/jmuSupplicant#3]
同mt7621 并没有在opnwrt官网上找到，请问如何获取

**Comment by MiChuancey** [comment]
https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/openwrt-toolchain-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz

**Comment by CChuancey** [comment]
> 同mt7621 并没有在opnwrt官网上找到，请问如何获取

下载链接：https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/openwrt-toolchain-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz

获取方式：
官网-->[Development Snapshot builds]-->ramips-->mt7621-->openwrt-sdk-ramips-mt7621-xxxxxxx

**Comment by GnaixEuy** [comment]
已成功编译，谢谢前辈
